---
name: "Split changes into list of Directories"
description: "Determine Directories with changes based on the inputs and returns the list of paths"
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
    required: true
    default: "${{ github.token }}"
  baseFolders:
    description: >
      A JSON encoded array of base directories
    required: true
    default: "."
  configFile:
    description: >
      Path to the config file that contains config.
    required: false
    default: ".github/config/splitter-config.yaml"
  depth:
    description: >
      Configure whether subdirectories need to be returned
    required: true
    default: "0"
  includeParent:
    description: >
      Include parent in front of each directory
    required: true
    default: "true"
  getAllDirectories:
    description: >
      Instead of finding the changed directories, return
      all the dirs
    required: false
    default: "false"
  requireHeadAheadOfBase:
    description: >
      Require the HEAD commit to be ahead of the base commit
    required: false
    default: "true"
  overrideDirectories:
    description: >
      A JSON encoded array of Directories to return instead of finding
      the changed Directories
    required: false
    default: "[]"
outputs:
  directories:
    description: >
      An array of all the directories that contain changes
runs:
  using: "node16"
  main: "../lib/split-changes-into-dirs.js"
